### ISSUE TITLE
官网无法正常浏览

### ISSUE THREAD

**Issue by mytharcher** [ecomfe/fontmin#6] opened 2015-04-20 15:27 UTC
Mac 10.9.5, Chrome 41

首页的魔方只能看到上半部分，打开后 Chrome 占的 CPU 随即狂飙到顶，然后一直卡死直至崩溃，自发布日至今都这样。

**Comment by junmer** [comment] 2015-04-20 16:07
@mytharcher 前辈 你好，多谢反馈
我的机器是 mac 10.10.3, Chrome 42.0.2311.90 ，没有发现你这个问题
可以帮我看一下 开发者工具么，有没有网络异常，或者 js 报错
谢谢 :smiley:

**Comment by mytharcher** [comment] 2015-04-21 00:52
今天魔方能看完整了，但没有报错和异常，一旦打开 CPU  马上 100%，然后 tab 标签都无法点击关闭，只能任务管理器结束进程。

**Comment by vadimsmirnovnsk** [comment] 2015-04-21 08:01
有网旦打开!  
旦打开 旦错和 CPU, 签 无法点 旦 OS 结束进 管 deprecated.

**Comment by junmer** [comment] 2015-04-21 09:04
@vadimsmirnovnsk  thanks for your case, could you tell me the os and browser you are using? so I can location problem. :smiley:

**Comment by junmer** [comment] 2015-04-22 11:59
hi @mytharcher @vadimsmirnovnsk 
I update homepage's font just now. I'm not sure if it works. please have a try. 
[zh-cn](http://ecomfe.github.io/fontmin/) or [en-us](http://ecomfe.github.io/fontmin/en)
deeply thanks

**Comment by mytharcher** [comment] 2015-04-22 15:17
@junmer It works now! Really thanks!

And it would be very kind of you if let me know what happens? Didn't find any commits you push to the site.

**Comment by junmer** [comment] 2015-04-23 03:42
@mytharcher :smiley: actually, The problem is #4 .
We miss the font hint info before latest version. 
so, I add the option `hinting` defaults true. see: [changlog\#0.7.3](https://github.com/ecomfe/fontmin/blob/master/CHANGELOG.md#073-2015-04-22)
then, rebuild the [site](https://github.com/fontmin/fontmin.github.io) , it works. :ok_hand: 
thank you very much.

**Comment by junmer** [comment] 2015-04-23 03:53
@vadimsmirnovnsk Сэр, в вашем браузере работает?

**Comment by junmer** [comment] 2015-05-20 03:41
@mytharcher @vadimsmirnovnsk  How time flies. Can i close this issue?

**Comment by mytharcher** [comment] 2015-05-20 15:29
I am OK about this.

**Closed** 2015-12-23 16:22 UTC
